openapi: 3.0.0
info:
  title: Config API
  version: 1.0.0
  description: API for Pocketmoney frontend

servers:
  - url: 'http://localhost:3001'
    description: 'Development server'
  - url: 'http://localhost:3001'
    description: 'Production server'

paths:
  /config/mandatoryExpenses/list:
    get:
      summary: Get list of Mandatory expenses
      description: Returns list of mandatory expenses
      tags:
        - mandatory expenses
      responses:
        200:
          description: Successful response

  /config/mandatoryExpenses/new:
    get:
      summary: Add new mandatory expense
      tags:
        - mandatory expenses
      responses:
        200:
          description: Successful response