name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout code 
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build the Docker image
        run: |
          docker build . --file be.Dockerfile --tag petrkuba/pk:pocketmoney_be
          docker push petrkuba/pk:pocketmoney_be
      -
        name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST}}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo docker pull petrkuba/pk:pocketmoney_be
            sudo docker stop pocketmoney-be
            sudo docker rm pocketmoney-be
            sudo docker run -d \
              -p 3001 \
              -e MONGODB_DATABASE_NAME=pocketmoney \
              --net pocketmoney-network \
              --name pocketmoney-be \
              petrkuba/pk:pocketmoney_be
            
          
